name: Sarwari IE Bank Infrastructure Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - '.github/workflows/ie-bank-infra.yml'

jobs:
  build_and_deploy_infrastructure:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Infrastructure Build Steps
    - name: Build Infrastructure
      run: |
        az bicep install
        az bicep build --file infra/main.bicep

    # Infrastructure Deployment Steps
    - name: Deploy Infrastructure
      run: |
        az deployment group create \
          --name ieBankDeployment \
          --resource-group [Your Resource Group Name] \
          --template-file infra/main.bicep \
          --parameters infra/parameters/dev.parameters.json \
          --parameters administratorLogin=${{ secrets.DBUSER }} \
          --parameters administratorLoginPassword=${{ secrets.DBPASS }}

    

