name: app-backend-papilioaureus 
on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/ie-bank-backend.yml'

env:
  BACKEND_WEBAPP_DEV: papilioWebApp
jobs:
  build:
    
    runs-on: ubuntu-latest
    env:
      ENV: ghci

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Upgrade PIP
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8 pytest 
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
            python -m pytest tests/unit -v
            python -m pytest tests/functional -v
    
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: app-backend-papilioaureus
          path: backend/

      


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v2
          with:
            name: python-app
            path: .
    
        - uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      
        - name: 'Deploy to Azure Web App'

            uses: azure/webapps-deploy@v2
            id: deploy-to-webapp
            with:
              app-name: ${{ env.BACKEND_WEBAPP_DEV }}
              package: .
    