name: app-backend-SARWARI #UPDATE WITH YOUR STUDENT ALIAS

on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/ie-bank-backend.yml'

env:
  BACKEND_WEBAPP_DEV: #Exercise III: set the name of your web app

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV: ghci

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip
        working-directory: ./backend

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./backend

      - name: Install flake8 and pytest
        run: pip install flake8 pytest
        working-directory: ./backend

      - name: Check syntax with flake8
        run: flake8 .
        working-directory: ./backend

      - name: Run tests with pytest
        run: pytest
        working-directory: ./backend

      - name: Upload packaged code as a GitHub artifact
        uses: actions/upload-artifact@v2
        with:
          name: packaged-code
          path: backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: packaged-code

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.BACKEND_WEBAPP_DEV }}
          slot-name: production
          package: packaged-code