name: app-backend-LeonardoMuci 
on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/ie-bank-backend.yml'

env:
  BACKEND_WEBAPP_DEV: LeoWebapp

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV: ghci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: pip install --upgrade pip
        working-directory: ./backend

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./backend

      - name: Install flake8 and pytest
        run: |
          pip install flake8 pytest
          flake8 .
        working-directory: ./backend

      - name: Run tests
        run: pytest
        working-directory: ./backend

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: packaged-code
          path: ./backend/**/*


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Exercise IV
      # GitHub action: Write download build artifact
    
      # Exercise IV
      # GitHub action: Write step to login in to Azure. You can use the repository secret AZURE_CREDENTIALS

      # Exercise IV
      # GitHub action: Write step to deploy the downloaded artifact to your Azure web app
    
